### ISSUE TITLE
HER demo dismissible alert fixes / enhancements

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-her#1074]
@ryan86 Thanks for getting this started!

I think we need a few enhancements/fixes to finish this off:

(1)  I notice it seems to not appear again if I reload the page (a cookie or something?). That's fine. But it would be good to have a clear understanding of the expected behavior so I can communicate it to the GCI staff.

(2) On initial load it looks like the size needs some fixes so the text has enough space.  When one changes the window size, the text inside the alert can bleed outside of the alert area. See image:

![image](https://github.com/archesproject/arches-her/assets/1286742/9dcd6234-ada7-4e29-9e5b-2802ac2a8e1a)

(3) After dismissing the alert, it pops up again once you scroll down. One needs to reload the page for the alert to disappear.

**Comment by ryan86** [comment]
@ekansa no problem. see my notes below.

1.) When the x is clicked the popup sets a flag in local storage that says the popup has already been displayed. As long as the user is still in that browser session that flag will be there in local storage and the popup will not be displayed. If the user creates a new browser session or deletes that flag manually then the popup should reappear.

2.) This should be fixed in the latest.

3.) I'm not seeing this behavior. Please test again when the latest is deployed.

**Comment by ekansa** [comment]
Yes! I can confirm this looks good to me and is behaving as expected on the demo site! Thanks!!
