### ISSUE TITLE
upgrade v7 - side nav popup has extra arrows on some pages

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1200]
Appears to affect the report, resource and graph designer pages - maybe others. Search appears fine.

![Image](https://github.com/archesproject/arches-her/assets/25295526/330d02c4-a9b0-4322-bd51-eab994971f32)

**Comment by samuelscandrett** [comment]
Months ago I also saw this whilst doing regular Arches dev work - I think it ended up being caused by switching between V7.6 and V7.5 and the wrong front-end dependencies being installed, maybe the datatables issue was in there too...  

I haven't been able to replicate it since, so I cannot confirm what actually was the cause, though I'll keep trying.

@phudson-he

**Comment by phudson-he** [comment]
This is a core issue.

Core issue: https://github.com/archesproject/arches/issues/11031
Core PR: https://github.com/archesproject/arches/pull/11032

**Comment by phudson-he** [comment]
Closing as fixed by https://github.com/archesproject/arches/pull/11032
