### ISSUE TITLE
Support child cards in workflow steps

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#132]
Cards for a child node nested beneath a semantic node do not appear in workflow steps. In order to display the card, the workflow step will need to generate a parent tile.

**Comment by robgaston** [comment]
we should think this through carefully... is this something that can be fixed by editing the models? if not, what happens if the parent has cardinality of `n`?  Seems to me like there are many cases where we simply cannot (practically speaking) automatically generate a parent tile.  I would say that if we are going to auto-generate a parent tile it should be done by the workflow viewmodel rather than by the workflow step (which can already be seeded with a parent tile id)

**Comment by chiatt** [comment]
Resolved through graph changes rather than support of child cards
