### ISSUE TITLE
Add Reference Numbers workflow step

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#27]
![Screen Shot 2019-05-01 at 4.18.52 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/db32b3b1-60dd-49b4-b3af-22f410033dc5)

<img width="1137" alt="Screen Shot 2019-05-01 at 4 21 53 PM" src="https://user-images.githubusercontent.com/1877663/57049540-4fd1fa00-6c2d-11e9-9489-b98fc8d14e7d.png">

**Comment by robgaston** [comment]
@chiatt I've reviewed the code here and assigned to you for a functional QA - thanks!

**Comment by chiatt** [comment]
This looks really good and is very close to done. There is an issue with values persisting when a reference number is removed from the list on the right: http://recordit.co/ubnJo4ychh
Also - the css could be a bit closer to the mockup. The right side of the title, 'Add Reference Number' is flush with the outside container rather than positioned over the card and the list of instances on the right should probably be in a somewhat darker panel.

**Comment by whatisgalen** [comment]
Assigned @dwuthrich to approve UI, @chiatt to approve the viewmodel and template changes.

**Comment by whatisgalen** [comment]
Following up on a conversation between myself, @robgaston and @dwuthrich , this step still needs some work in the way of two distinct buttons to add new tiles and proceed to the next step. Right now "Add" adds only one tile and then proceeds to the next step, and then the user has to click the "back" arrow in order to add more tiles. This issue almost certainly extends beyond the scope of just this step and affects any step where the user adds multiple tiles from the same card. Therefore I'm making a new issue to address such a general case.

**Comment by dwuthrich** [comment]
This step still needs work.  When initially encountered, there is no UI that alerts user that multiple tiles can be created.  When returning to this card in an active workflow (e.g.: going back to this step), there is no indication of how to move past this step: https://recordit.co/fuJ9OrdxHI

**Comment by whatisgalen** [comment]
just merged in some changes, requesting feedback for QA @dwuthrich

**Comment by dwuthrich** [comment]
meets requirements
