### ISSUE TITLE
Consultation workflow allows user to complete the workflow before all required steps have been completed

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#384]
See: https://recordit.co/OzZHAW1JAG

User must enter consultation related information before the finish button should be enabled

**Comment by whatisgalen** [comment]
@dwuthrich @chiatt 
FYI: Because there are two ways to advance to the next step (either clicking the right-arrow at top, or clicking "Add" to autoadvance to next step), in order to enforce Requirement, both the workflow step config `required` has to be true *and* the card corresponding to the nodegroup of the step must also be marked `required` in the graph.

**Comment by whatisgalen** [comment]
@dwuthrich this change requires package re-load to take effect

**Comment by dwuthrich** [comment]
meets requirements
