### ISSUE TITLE
Map default zoom level setting is not respected

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/arches-her#629]
The search/find page map default zoom does not seem to be using the default zoom value because the default zoom level stays the same regardless of what value is set as the default zoom in the Default Map Settings. When forcing refresh the map zooms out to the set Project Extent, and then zooms back to the original level.

Questions: 

* Is this how the default zoom value should work or if not how do we set the default zoom level? 
* Is the default zoom level possibly hard coded?
* Should the default zoom level reflect the Project Extent instead of the default zoom value?

Steps to reproduce:
1) Open the search page (eg. https://esriarches.fargeo.com/arches-her/search)

2) Navigate to System Settings from the left hand side navigation bar

3) Click on Default Map Settings - and then on Map Zoom

4) Set the default zoom to 20 and click save

5) Go back to the search page using the navigation bar - the map zoom level remains the same as before. If set to 20, it would be expected that the zoom level is at it's maximum like so:

![32213e8d-e0d9-4acc-b417-0e9b37550990](https://user-images.githubusercontent.com/59013689/117162519-be1c9a80-adba-11eb-8296-4e830e7543a6.png)

6) Go back to System Settings - Default Map Settings and set the Default Zoom value back to 6.

The current zoom level that does not change when the default zoom value is changed:
![8eabe007-4e98-4638-b4c7-d10b7bfad4ad](https://user-images.githubusercontent.com/59013689/117162603-d55b8800-adba-11eb-93f8-d47868971f0c.png)

No hard coded extent or zoom should be stored in Arches HER, other than when this is saved as an implementation-specific setting.

**Comment by chiatt** [comment]
Thanks @chrisdolby-HE, this is a good question and we should update the Map Zoom card to explain how default zoom is used. Currently the default zoom applies to the map card and the map widget, but not to search. This is because search will automatically zoom to the extent of the data in the active page of your search results, trumping whatever the default might be. If the default zoom were to be applied, all the data in your search results might not be visible at that zoom level.

If there are no features in your search results, or there are simply no search results at all, the map will zoom to your project's extent. In this case the map should probably just center on the project and zoom to the default zoom, but generally there are features on the map or the default zoom isn't too different from the project extent. Nevertheless, the default zoom should probably apply in this case as well just to be consistent and avoid any confusion.

**Comment by chrisdolby-HE** [comment]
Hi @chiatt - thanks for this. I appreciate the explanation.

**Comment by aj-he** [comment]
Closing as appears to have answered the question.
